export const airplaneTypes = [
  { id: 0, cat: 'other', name: 'Unknown', icon: 'unknown' },
  { id: 1, cat: 'air', name: 'Glider', icon: 'glider' },
  { id: 2, cat: 'air', name: 'Tow', icon: 'towplane' },
  { id: 3, cat: 'air', name: 'Helicopter', icon: 'helicopter' },
  { id: 4, cat: 'air', name: 'Parachute', icon: 'paraglider' },
  { id: 5, cat: 'air', name: 'Drop Plane', icon: 'plane' },
  { id: 6, cat: 'air', name: 'Hang Glider', icon: 'hangglider' },
  { id: 7, cat: 'air', name: 'Paraglider', icon: 'paraglider' },
  { id: 8, cat: 'air', name: 'Plane', icon: 'plane' },
  { id: 9, cat: 'air', name: 'Jet', icon: 'jet' },
  { id: 10, cat: 'air', name: 'UFO', icon: 'ufo' },
  { id: 11, cat: 'air', name: 'Balloon', icon: 'balloon' },
  { id: 12, cat: 'air', name: 'Airship', icon: 'blimp' },
  { id: 13, cat: 'air', name: 'Drone', icon: 'drone' },
  { id: 15, cat: 'other', name: 'Static Object', icon: 'tower' },
  { id: 16, cat: 'air', name: 'Gyrocopter', icon: 'gyro' },
  { id: 17, cat: 'air', name: 'Paramotor', icon: 'paraglider' },
  { id: 18, cat: 'air', name: 'Cropduster', icon: 'cropduster' },
  { id: 19, cat: 'air', name: 'Rocket', icon: 'rocket' },
  { id: 20, cat: 'other', name: 'Person', icon: 'person' },
  { id: 21, cat: 'ground', name: 'Shipping Container', icon: 'container' },
  { id: 22, cat: 'ground', name: 'Car', icon: 'car' },
  { id: 23, cat: 'ground', name: 'Van', icon: 'van' },
  { id: 24, cat: 'ground', name: 'Campervan', icon: 'van' },
  { id: 25, cat: 'ground', name: 'Caravan', icon: 'caravan' },
  { id: 26, cat: 'ground', name: 'Trailer', icon: 'trailer' },
  { id: 27, cat: 'ground', name: 'Glider Trailer', icon: 'glider-trailer' },
  { id: 28, cat: 'ground', name: 'Bicycle', icon: 'bicycle' },
  { id: 29, cat: 'ground', name: 'Scooter', icon: 'scooter' },
  { id: 30, cat: 'ground', name: 'Skateboard', icon: 'skateboard' },
  { id: 31, cat: 'ground', name: 'Heavy Truck', icon: 'heavy-truck' },
  { id: 32, cat: 'ground', name: 'Light Truck', icon: 'light-truck' },
  { id: 33, cat: 'ground', name: 'Motorbike', icon: 'motorbike' },
  { id: 34, cat: 'ground', name: 'Train', icon: 'train' },
  { id: 35, cat: 'ground', name: 'Go-Cart', icon: 'go-cart' },
  { id: 36, cat: 'water', name: 'Hovercraft', icon: 'hovercraft' },
  { id: 37, cat: 'water', name: 'Yacht', icon: 'yacht' },
  { id: 38, cat: 'water', name: 'Fishing Boat', icon: 'fishing-boat' },
  { id: 39, cat: 'water', name: 'Dinghy', icon: 'dinghy' },
  { id: 40, cat: 'water', name: 'Boat', icon: 'boat' },
  { id: 41, cat: 'water', name: 'Catamaran', icon: 'catamaran' },
  { id: 42, cat: 'water', name: 'Houseboat', icon: 'houseboat' },
  { id: 43, cat: 'water', name: 'Trawler', icon: 'trawler' },
  { id: 44, cat: 'water', name: 'Ship', icon: 'ship' },
  { id: 45, cat: 'water', name: 'Canoe', icon: 'canoe' },
  { id: 46, cat: 'water', name: 'Kayak', icon: 'kayak' },
  { id: 47, cat: 'ground', name: 'Pickup/Ute', icon: 'pickup-ute' },
  { id: 48, cat: 'air', name: 'Sea Plane', icon: 'plane' },
  { id: 49, cat: 'air', name: 'Amphibian', icon: 'plane' },
  { id: 50, cat: 'air', name: 'Tiltrotor', icon: 'plane' },
  { id: 51, cat: 'air', name: 'Jet Super', icon: 'jet' },
  { id: 52, cat: 'air', name: 'Jet Heavy', icon: 'jet' },
  { id: 53, cat: 'air', name: 'Jet Medium', icon: 'jet' },
  { id: 54, cat: 'air', name: 'Jet Light', icon: 'jet' },
  { id: 55, cat: 'air', name: 'Turboprop Heavy', icon: 'plane' },
  { id: 56, cat: 'air', name: 'Turboprop Medium', icon: 'plane' },
  { id: 57, cat: 'air', name: 'Turboprop Light', icon: 'plane' },
  { id: 58, cat: 'air', name: 'Plane Twin Engine', icon: 'plane' },
  { id: 59, cat: 'ground', name: 'Horse', icon: 'horse' },
  { id: 60, cat: 'water', name: 'Shark', icon: 'shark' },
  { id: 61, cat: 'water', name: 'Sail Boat', icon: 'sailboat' },
  { id: 62, cat: 'water', name: 'Tanker', icon: 'tanker' },
  { id: 63, cat: 'other', name: 'Unknown Skylines', icon: 'unknown-skylines' },
  { id: 64, cat: 'ground', name: 'Milk Tanker', icon: 'milk-tanker' },
  { id: 65, cat: 'other', name: 'Hiker', icon: 'hiker' },
  { id: 66, cat: 'water', name: 'Swimmer', icon: 'swimmer' },
  { id: 67, cat: 'ground', name: 'Skier', icon: 'skier' },
  { id: 68, cat: 'ground', name: 'Mountain Biker', icon: 'mountain-biker' },
  { id: 69, cat: 'ground', name: 'Biker', icon: 'biker' },
  { id: 70, cat: 'ground', name: 'Cyclist', icon: 'cyclist' },
  { id: 71, cat: 'water', name: 'Raft', icon: 'raft' },
  { id: 72, cat: 'water', name: 'Kite Surfer', icon: 'kite-surfer' },
  { id: 73, cat: 'water', name: 'Wind Surfer', icon: 'wind-surfer' },
  { id: 74, cat: 'water', name: 'Downwind Foiler', icon: 'downwind-foiler' },
  { id: 75, cat: 'water', name: 'Wing Foiler', icon: 'wing-foiler' },
  { id: 76, cat: 'water', name: 'Surfer', icon: 'surfer' },
  { id: 77, cat: 'water', name: 'Wind Surfer', icon: 'wind-surfer' },
  { id: 78, cat: 'water', name: 'Paddle Boarder', icon: 'paddle-boarder' },
  { id: 79, cat: 'ground', name: 'Forklift', icon: 'forklift' },
];
