name: CI

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - run: npx nx format:check
      - run: npx nx affected -t stylelint --output-style=stream
      - run: npx nx affected -t build --output-style=stream
      - run: npx nx affected -t test --output-style=stream
      - run: npx nx affected -t lint --output-style=stream
      - run: npx nx affected -t component-test --output-style=stream
