name: deploy navigation to stork web
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_MAP_TILES_KEY: ${{ secrets.NX_MAP_TILES_KEY }}
      NX_LIGHT_GALLERY_KEY: ${{ secrets.NX_LIGHT_GALLERY_KEY }}
      NX_API_DB_URL: ${{ vars.NX_API_DB_URL }}
      NX_NOTAM_PROXY: ${{ vars.NX_NOTAM_PROXY }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_SERVER: ${{ vars.FTP_SERVER }}
      FTP_USERNAME: ${{ vars.FTP_USERNAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - name: Build map
        run: npx nx build mapview
      - name: FTP Sync files
        run: npx nx affected -t deploy --output-style=stream
      - run: npx nx-cloud stop-all-agents
