name: deploy mapview
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_MAP_TILES_KEY: ${{ secrets.NX_MAP_TILES_KEY }}
      NX_LIGHT_GALLERY_KEY: ${{ secrets.NX_LIGHT_GALLERY_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - name: Build map
        run: npx nx build mapview --base-href /laamap/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/apps/mapview
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - run: npx nx-cloud stop-all-agents
